### ISSUE TITLE
Error after upgrade to Paloma v1.3.1: Reactor validation error: wrong Block.Header.AppHash.

### ISSUE THREAD

**Issue by alipostaci2001** [palomachain/paloma#894] opened 2023-06-26 20:35 UTC
https://gist.github.com/alipostaci2001/548eed1ab2cf61da6f492a1073198a81

the page of the explorer before the upgrade :
![image](https://github.com/palomachain/paloma/assets/42353945/4af84eec-cddb-4500-8fa9-4a88577bd545)

**Comment by taariq** [comment] 2023-06-26 20:39
We need some more information:
1. Versions you were at before the upgrade.
2. Versions you were at after the upgrade
3. The block number in which you experienced the apphash

**Comment by alipostaci2001** [comment] 2023-06-26 20:53
1- my paloma and pigeon version before the update :
paloma version : 1.2.0
pigeon version :1.1.1

2- after the upgrade :
paloma version : 1.3.1
pigeon version :1.2.1

3-most likely first blocks after the update..

**Comment by taariq** [comment] 2023-06-26 21:25
Are you able to sync from snapshot?

**Comment by midoranode** [comment] 2023-06-27 02:39
Got the same problem. Tried to load snapshot from 2110000. Everything goes fine at first but then:
`4:22AM INF executed block height=2111425 module=state num_invalid_txs=0 num_valid_txs=14
4:22AM INF commit synced commit=436F6D6D697449447B5B313920313334203139372031313220313339203936203331203235322031303920323230203231382031383420313935203134362032303820313830203239203139342031323920313836203633203232352031303120333220343220343720323235203931203932203138332031393820395D3A3230333743317D module=server
4:22AM INF committed state app_hash=1386C5708B601FFC6DDCDAB8C392D0B41DC281BA3FE165202A2FE15B5CB7C609 height=2111425 module=state num_txs=14
4:22AM ERR Error in validation err="wrong Block.Header.AppHash.  Expected 1386C5708B601FFC6DDCDAB8C392D0B41DC281BA3FE165202A2FE15B5CB7C609, got E864C5293AFDF6CBB42C5818477588FA7620C144A650D71021DD56A9B72559A0" module=blockchain
4:22AM ERR Stopping peer for error err="Reactor validation error: wrong Block.Header.AppHash.  Expected 1386C5708B601FFC6DDCDAB8C392D0B41DC281BA3FE165202A2FE15B5CB7C609, got E864C5293AFDF6CBB42C5818477588FA7620C144A650D71021DD56A9B72559A0" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}`

**Comment by taariq** [comment] 2023-06-27 02:40
Thanks @midoranode for the update and block height.

**Comment by taariq** [comment] 2023-06-27 04:52
Contents of the block `2111425` https://paloma.explorers.guru/block/2111425 which appears to have a Cosmwasm `execute contract` command that may be the offending tx to cause the AppHash.

**Comment by ToasterTheBrave** [comment] 2023-06-27 20:05
@midoranode or @alipostaci2001 Does this problem persist after syncing from a snapshot?  We saw something similar to this in testnet and I'm trying to reproduce.  I seem unable to reproduce it after syncing from a point after the bad block.

In our testnet case, the problem oddly seemed to be caused by cosmovisor.  Just to confirm, neither of you use cosmovisor to run palomad?

**Comment by midoranode** [comment] 2023-06-28 00:36
Three times I tried to use different snapshots from height above the problem but got same result. No cosmovisor.
`2:32AM INF indexed block exents height=2123444 module=txindex
2:32AM INF minted coins from module account amount=32822756ugrain from=mint module=x/bank
2:32AM INF abci-validator-size module=x/palomaconsensus
2:32AM INF validator jailed module=x/staking validator=palomavalcons17qk5hd5k0xxtt35qg8shqyfqthsdvvz7hr6uux
2:32AM INF jailing a validator module=x/valset reason="validator's pigeon has been inactive" val-addr=palomavaloper1nlwzcegm7kxg6rpmkqmpl3afvapkyp4msl7gwg
2:32AM INF trying to deploy smart contract to EVM chain chain-reference-id=bnb-main module=x/evm smart-contract-id=2
2:32AM INF trying to deploy smart contract to EVM chain chain-reference-id=eth-main module=x/evm smart-contract-id=2
2:32AM INF trying to deploy smart contract to all chains module=x/evm smart-contract-id=2
2:32AM INF executed block height=2123445 module=state num_invalid_txs=0 num_valid_txs=3
2:32AM INF commit synced commit=436F6D6D697449447B5B3820313830203234302031383520393120323532203235312036362032313920323136203136362031343820313720313437203135392031353020313939203232382032343320323031203133322031203231392031312032303820313832203138302031303620313139203131382031343120375D3A3230363642357D module=server
2:32AM INF committed state app_hash=08B4F0B95BFCFB42DBD8A69411939F96C7E4F3C98401DB0BD0B6B46A77768D07 height=2123445 module=state num_txs=3
2:32AM ERR Error in validation err="wrong Block.Header.AppHash.  Expected 08B4F0B95BFCFB42DBD8A69411939F96C7E4F3C98401DB0BD0B6B46A77768D07, got B71EF4BFF2C751DB5FA699EB0BA3643F68909CC78AAB5B97C513D9C1C15D6180" module=blockchain
2:32AM ERR Stopping peer for error err="Reactor validation error: wrong Block.Header.AppHash.  Expected 08B4F0B95BFCFB42DBD8A69411939F96C7E4F3C98401DB0BD0B6B46A77768D07, got B71EF4BFF2C751DB5FA699EB0BA3643F68909CC78AAB5B97C513D9C1C15D6180" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
2:32AM INF service stop impl={"Logger":{"Logger":{}}} module=p2p msg={} peer={"id":"9581fadb9a32f2af89d575bb0f2661b9bb216d41","ip":"46.4.23.108","port":26656}
2:32AM ERR Stopping peer for error err="read tcp 37.120.191.47:53194->46.4.23.108:26656: use of closed network connection" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
2:32AM INF service stop impl={"Data":{},"Logger":{"Logger":{}}} module=p2p msg={} peer={"id":"9581fadb9a32f2af89d575bb0f2661b9bb216d41","ip":"46.4.23.108","port":26656}
2:32AM ERR error while stopping peer error="already stopped" module=p2p
2:32AM ERR Stopping peer for error err="Reactor validation error: wrong Block.Header.AppHash.  Expected 08B4F0B95BFCFB42DBD8A69411939F96C7E4F3C98401DB0BD0B6B46A77768D07, got B71EF4BFF2C751DB5FA699EB0BA3643F68909CC78AAB5B97C513D9C1C15D6180" module=p2p peer={"Data":{},"Logger":{"Logger":{}}}
2:32AM INF service stop impl={"Logger":{"Logger":{}}} module=p2p msg={} peer={"id":"8af8dfa8`

**Comment by alipostaci2001** [comment] 2023-06-28 05:17
pigeon logs :

https://gist.github.com/alipostaci2001/51bbb657231c28fc171e0f3468175e3a

**Comment by ToasterTheBrave** [comment] 2023-06-28 13:41
I don't think Pigeon should be related.  This appears to be an issue with hashing the transactions in a block.  It's a bit difficult to debug without being able to reproduce because it's deep in either cosmos-sdk or cometbft code.

We need to verify a few more things to help us reproduce.
1. How did you get the binary, build or download?
2. What's the distro and version of your OS?
3. What is your Go version, if installed?
4. What's your GLIBC version?
5. What's the sha256sum of your current palomad binary?

**Comment by midoranode** [comment] 2023-06-29 02:39
1) Build 
2) Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-148-generic x86_64)
3) go version go1.20.2 linux/amd64
4) ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
5) 87a79abbab684ae18b69d9e5019b0fe98b49971868c6ac4db25dff70e24d660c  /usr/local/bin/palomad

**Comment by taariq** [comment] 2023-07-03 19:26
@midoranode looks like @alipostaci2001 was able to recover. We don't have further instances of this issue reported. Are you able to recover?

**Comment by midoranode** [comment] 2023-07-05 04:10
Yes, only on other server

**Comment by taariq** [comment] 2023-07-05 05:22
Okay. Closing for now until issue arises.

**Closed by taariq** 2023-07-05 05:22 UTC
Labels: bug, Mainnet
