### ISSUE TITLE
panic: unknown field "chains" in types.Params

### ISSUE THREAD

**Issue by rootedbox** [palomachain/paloma#335] opened 2022-07-21 16:33 UTC
# What is happening?
<details>
  <summary>When trying to run palomad the server panic crashes</summary>
<I>
did a standard installation of [Paloma](https://github.com/palomachain/paloma) following the instructions. When it comes time to turn on the server it dies in a panic state.

ssh rootedbox@rbox.palomachain.com

palomad start
12:18AM INF starting node with ABCI Tendermint in-process
12:18AM INF Starting multiAppConn service impl=multiAppConn module=proxy
12:18AM INF Starting localClient service connection=query impl=localClient module=abci-client
12:18AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
12:18AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
12:18AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
12:18AM INF Starting EventBus service impl=EventBus module=events
12:18AM INF Starting PubSub service impl=PubSub module=pubsub
12:18AM INF Starting IndexerService service impl=IndexerService module=txindex
12:18AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=v0.3.0-alpha
12:18AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
12:18AM INF asserting crisis invariants inv=0/11 module=x/crisis name=bank/nonnegative-outstanding
12:18AM INF asserting crisis invariants inv=1/11 module=x/crisis name=bank/total-supply
12:18AM INF asserting crisis invariants inv=2/11 module=x/crisis name=gov/module-account
12:18AM INF asserting crisis invariants inv=3/11 module=x/crisis name=distribution/nonnegative-outstanding
12:18AM INF asserting crisis invariants inv=4/11 module=x/crisis name=distribution/can-withdraw
12:18AM INF asserting crisis invariants inv=5/11 module=x/crisis name=distribution/reference-count
12:18AM INF asserting crisis invariants inv=6/11 module=x/crisis name=distribution/module-account
12:18AM INF asserting crisis invariants inv=7/11 module=x/crisis name=staking/module-accounts
12:18AM INF asserting crisis invariants inv=8/11 module=x/crisis name=staking/nonnegative-power
12:18AM INF asserting crisis invariants inv=9/11 module=x/crisis name=staking/positive-delegation
12:18AM INF asserting crisis invariants inv=10/11 module=x/crisis name=staking/delegator-shares
12:18AM INF asserted all invariants duration=2.160309 height=0 module=x/crisis
12:18AM INF created new capability module=ibc name=ports/transfer
12:18AM INF port binded module=x/ibc/port port=transfer
12:18AM INF claimed capability capability=1 module=transfer name=ports/transfer
panic: unknown field "chains" in types.Params

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0xc000f36230?, {0xc0000f4cf0?, 0xc0010f90e0?, 0x25b77e0?}, {0x25c94d0?, 0x3637af0?})
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/codec/proto_codec.go:176 +0x45
github.com/palomachain/paloma/x/evm.AppModule.InitGenesis({{{0x25d9be0, 0xc000fab6d0}}, {{0x25d9be0, 0xc000fab6d0}, {0x25ba7a0, 0xc000da5b10}, {0x25ba7a0, 0x0}, {{0x25d9be0, 0xc000fab6d0}, ...}, ...}, ...}, ...)
	/app/x/evm/module.go:153 +0x62
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x25ce768, 0xc0000d6000}, {0x25db300, 0xc000fb8b80}, {{0x0, 0x0}, {0xc000266770, 0x10}, 0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/types/module/module.go:320 +0x29d
github.com/palomachain/paloma/app.(*App).InitChainer(_, {{0x25ce768, 0xc0000d6000}, {0x25db300, 0xc000fb8b80}, {{0x0, 0x0}, {0xc000266770, 0x10}, 0x0, ...}, ...}, ...)
	/app/app/app.go:684 +0x20e
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc0010b1040, {{0xab046b1, 0xeda4fb12c, 0x0}, {0xc000266770, 0x10}, 0xc00004ebc0, {0x3637af0, 0x0, 0x0}, ...})
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:62 +0x455
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000f2d9e0, {{0xab046b1, 0xeda4fb12c, 0x0}, {0xc000266770, 0x10}, 0xc00004ebc0, {0x3637af0, 0x0, 0x0}, ...})
	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:272 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x3?, {{0xab046b1, 0xeda4fb12c, 0x0}, {0xc000266770, 0x10}, 0xc00004ebc0, {0x3637af0, 0x0, 0x0}, ...})
	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x1c9bf05, 0x7}}, {0xc000266770, 0x10}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:319 +0xd78
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000e67f68, {0x25dbcf8, 0xc000208a90})
	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x1c9bf05, 0x7}}, {0xc000266770, 0x10}, 0x1, 0x0, ...}, ...)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc000fcd180, {0x25cb630, 0xc0001efae0}, 0xc001140d90, {0x25b5880, 0xc0000c84e0}, 0x0?, 0x0?, 0xc001140fa0, {0x25cf610, ...}, ...)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x577
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x25e2460, 0xc0010d3080}, {0x0, 0x0}, {0x25d2980, 0xc000fab6d0}, ...}, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:272 +0x7db
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000ff8500?, {0x3637af0?, 0x0?, 0x0?})
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:126 +0x169
github.com/spf13/cobra.(*Command).execute(0xc000ff8500, {0x3637af0, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000fb1400)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x237cb98?, {0xc000c8d5f0, 0x17})
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/server/cmd/execute.go:36 +0x1eb
main.main()
	/app/cmd/palomad/main.go:52 +0xc5</i>
</details>

# How to reproduce?
<details>
  <summary>Steps to Reproduce</summary>
  <i>ssh rootedbox@rbox.palomachain.com<br>
paloma start
</i>
</details>

**Comment by measure-fi** [comment] 2022-07-21 17:20
Duplicate of https://github.com/palomachain/paloma/issues/331

**Closed by measure-fi** 2022-07-21 17:20 UTC
Labels: bug
